# Generated by Django 4.1.7 on 2023-04-12 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perfil_proveedor', '0005_profile_proveedor_anio_nacimiento_and_more'),
        ('prov_servis', '0001_initial'),
        ('login_vendedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Afiliacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(default='Pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('proveedor_afiliacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='afiliaciones', to='perfil_proveedor.profile_proveedor')),
                ('vendedor_afiliacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='afiliaciones', to='login_vendedor.profile_vendedor')),
            ],
            options={
                'verbose_name': 'afiliaciones',
            },
        ),
        migrations.CreateModel(
            name='CrearServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provincia', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('whatsapp', models.CharField(default='000 000 0000', max_length=20)),
                ('telefono', models.CharField(default='000 000 0000', max_length=20)),
                ('nombre_proyecto', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(max_length=500)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_disponible_cotizacion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(default='Pendiente', max_length=30)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('comision_vendedor', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_estimada_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_estimada_conclusion', models.DateTimeField(blank=True, null=True)),
                ('afiliacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='dashboard_prov.afiliacion')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil_proveedor.profile_proveedor')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prov_servis.servicio_prov')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_vendedor.profile_vendedor')),
            ],
            options={
                'verbose_name': 'servicio',
                'verbose_name_plural': 'servicios',
            },
        ),
    ]
