# Generated by Django 4.1.7 on 2023-04-12 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_vendedor', '0001_initial'),
        ('perfil_proveedor', '0005_profile_proveedor_anio_nacimiento_and_more'),
        ('prov_servis', '0001_initial'),
        ('dashboard_prov', '0002_remove_crearservicio_ciudad_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CrearServicio',
            new_name='CrearProyecto',
        ),
    ]
