# Generated by Django 4.1.7 on 2023-04-13 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_prov', '0003_rename_crearservicio_crearproyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='crearproyecto',
            name='codigo_unico_proyect',
            field=models.CharField(default='NULL', editable=False, max_length=7, unique=True, verbose_name='Código Único'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crearproyecto',
            name='nombre_proyecto',
            field=models.CharField(blank=True, default='Null', max_length=100, null=True),
        ),
    ]
