# Generated by Django 4.1.7 on 2023-04-13 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil_proveedor', '0005_profile_proveedor_anio_nacimiento_and_more'),
        ('vend_config_inic', '0003_metodo_pago_vendedor_nombre_banco_and_more'),
        ('login_vendedor', '0002_rename_codigo_unico_proveedor_profile_vendedor_codigo_unico_vendedor'),
        ('dashboard_prov', '0005_crearproyecto_contacto_vendedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crearproyecto',
            name='contacto_vendedor',
        ),
        migrations.AddField(
            model_name='crearproyecto',
            name='contact_vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vend_config_inic.contacto_vendedor'),
        ),
        migrations.AlterField(
            model_name='crearproyecto',
            name='afiliacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='dashboard_prov.afiliacion'),
        ),
        migrations.AlterField(
            model_name='crearproyecto',
            name='codigo_unico_proyect',
            field=models.CharField(blank=True, editable=False, max_length=7, null=True, unique=True, verbose_name='Código Único'),
        ),
        migrations.AlterField(
            model_name='crearproyecto',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='perfil_proveedor.profile_proveedor'),
        ),
        migrations.AlterField(
            model_name='crearproyecto',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login_vendedor.profile_vendedor'),
        ),
    ]
