# Generated by Django 4.1.7 on 2023-04-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_prov', '0008_estado_comision_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='crearproyecto',
            name='estado_de_comision_vend',
            field=models.CharField(default='Pendiente', max_length=30),
        ),
    ]
