# Generated by Django 4.1.7 on 2023-04-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_prov', '0009_crearproyecto_estado_de_comision_vend'),
    ]

    operations = [
        migrations.AddField(
            model_name='crearproyecto',
            name='nombre_cliente',
            field=models.CharField(blank=True, default='Nombre cliente', max_length=70, null=True),
        ),
    ]
