# Generated by Django 4.1.5 on 2023-04-30 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_prov', '0010_crearproyecto_nombre_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crearproyecto',
            name='codigo_unico_proyect',
            field=models.CharField(blank=True, editable=False, max_length=8, null=True, unique=True, verbose_name='Código Único'),
        ),
    ]
