# Generated by Django 4.1.5 on 2023-05-01 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_prov', '0012_alter_crearproyecto_codigo_unico_proyect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crearproyecto',
            name='apartamen_suite_proyec',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='crearproyecto',
            name='codigo_unico_proyect',
            field=models.CharField(blank=True, editable=False, max_length=15, null=True, unique=True, verbose_name='Código Único'),
        ),
        migrations.AlterField(
            model_name='crearproyecto',
            name='comision_prov',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='crearproyecto',
            name='comision_vendedor',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='crearproyecto',
            name='numero_proyec',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='crearproyecto',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
