# Generated by Django 4.1.5 on 2023-05-03 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_prov', '0015_alter_crearproyecto_apartamen_suite_proyec_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crearproyecto',
            name='fecha_conclusion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
