# Generated by Django 4.1.5 on 2023-05-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_prov', '0016_crearproyecto_fecha_conclusion'),
    ]

    operations = [
        migrations.AddField(
            model_name='crearproyecto',
            name='fecha_pago_comision',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
