# Generated by Django 4.1.7 on 2023-05-04 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_vendedor', '0002_rename_codigo_unico_proveedor_profile_vendedor_codigo_unico_vendedor'),
        ('perfil_proveedor', '0005_profile_proveedor_anio_nacimiento_and_more'),
        ('dashboard_prov', '0017_crearproyecto_fecha_pago_comision'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comisiones_vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_vendedor_comision', models.CharField(blank=True, default='NULL', max_length=150, null=True)),
                ('nombre_proveedor_vend', models.CharField(blank=True, default='NULL', max_length=80, null=True)),
                ('nombre_proyect_vend', models.CharField(blank=True, default='NULL', max_length=80, null=True)),
                ('nombre_servicio_vend', models.CharField(blank=True, default='NULL', max_length=80, null=True)),
                ('codigo_unico_proyecto', models.CharField(blank=True, default='NULL', max_length=15, null=True)),
                ('comision', models.CharField(blank=True, default='NULL', max_length=20, null=True)),
                ('metodo_cobro_vend', models.CharField(blank=True, default='NULL', max_length=50, null=True)),
                ('tipo_document_id_vend', models.CharField(blank=True, default='NULL', max_length=15, null=True)),
                ('nombre_completo_id_vend', models.CharField(blank=True, default='NULL', max_length=100, null=True)),
                ('nombre_banco_vend', models.CharField(blank=True, default='NULL', max_length=50, null=True)),
                ('numero_cuenta_bancaria_vend', models.CharField(blank=True, default='NULL', max_length=100, null=True)),
                ('provincia_vend_comi', models.CharField(blank=True, default='provin_vend_comision', max_length=30, null=True)),
                ('ciudad_vend_comi', models.CharField(blank=True, default='Nombre cliente', max_length=30, null=True)),
                ('direccion_vendedor_comi', models.CharField(blank=True, default='derc_vend_comision', max_length=150, null=True)),
                ('codigo_factura_comision_ved', models.CharField(blank=True, editable=False, max_length=17, null=True, unique=True, verbose_name='Código_factura_comisión')),
                ('fecha_facturacion', models.DateTimeField(auto_now_add=True)),
                ('proveedor_comi_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proveedor_comision_fk', to='perfil_proveedor.profile_proveedor')),
            ],
            options={
                'verbose_name': 'comisiones_vendedor',
                'verbose_name_plural': 'comisiones_vendedores',
            },
        ),
        migrations.AlterModelOptions(
            name='crearproyecto',
            options={'verbose_name': 'crearproyecto', 'verbose_name_plural': 'crearproyectos'},
        ),
        migrations.RemoveField(
            model_name='crearproyecto',
            name='fecha_pago_comision',
        ),
        migrations.DeleteModel(
            name='Estado_comision_vendedor',
        ),
        migrations.AddField(
            model_name='comisiones_vendedor',
            name='proyecto_comi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proyecto_comision', to='dashboard_prov.crearproyecto'),
        ),
        migrations.AddField(
            model_name='comisiones_vendedor',
            name='vendedor_comi_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendedor_comision_fk', to='login_vendedor.profile_vendedor'),
        ),
    ]
