# Generated by Django 4.1.7 on 2023-05-04 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_prov', '0018_comisiones_vendedor_alter_crearproyecto_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comisiones_vendedor',
            name='comision',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
    ]
