# Generated by Django 4.1.5 on 2023-05-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_prov', '0020_crearproyecto_fecha_pago_comision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crearproyecto',
            name='fecha_cancelacion_proyec',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crearproyecto',
            name='fecha_reanudacion_proyec',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crearproyecto',
            name='fecha_suspencion_proyec',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
