# Generated by Django 4.1.5 on 2023-05-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_prov', '0021_crearproyecto_fecha_cancelacion_proyec_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crearproyecto',
            name='comision_plataform',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='crearproyecto',
            name='estado_comis_plataform',
            field=models.CharField(default='NULL', max_length=20),
        ),
    ]
