# Generated by Django 4.1.7 on 2023-05-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_prov', '0022_crearproyecto_comision_plataform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crearproyecto',
            name='vend_confir_precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
