# Generated by Django 4.1.7 on 2023-05-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_prov', '0023_crearproyecto_vend_confir_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='crearproyecto',
            name='fecha_saldado_comis',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
