# Generated by Django 4.1.5 on 2023-05-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_prov', '0026_remove_comisiones_vendedor_ciudad_vend_comi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comisiones_vendedor',
            name='institucion_deposito',
            field=models.CharField(blank=True, default='NULL', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='afiliacion',
            name='estado',
            field=models.CharField(default='Aceptada', max_length=20),
        ),
    ]
