# Generated by Django 4.1.7 on 2023-04-08 02:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import prov_servis.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config_inicial_prov', '0004_alter_contacto_proveedor_numwhatsapp_and_more'),
        ('perfil_proveedor', '0005_profile_proveedor_anio_nacimiento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio_prov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servicio', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('imagen_servicio', models.ImageField(default='NULL', upload_to=prov_servis.models.tumtu_directory_path)),
                ('Comicion', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('contactoProveedor_forenkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config_inicial_prov.contacto_proveedor')),
                ('geoServiciosProveedor_forenkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config_inicial_prov.rango_servicio')),
                ('ubicacionProveedor_forenkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config_inicial_prov.ubicacion_proveedor')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicio', to='perfil_proveedor.profile_proveedor')),
            ],
            options={
                'verbose_name': 'servicios',
            },
        ),
        migrations.CreateModel(
            name='Post_prov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_serv', models.ImageField(default='imagen.jpg', upload_to=prov_servis.models.imgpost_directory_path)),
                ('imagen_serv_dos', models.ImageField(default='imagen.jpg', upload_to=prov_servis.models.imgpost_directory_path)),
                ('imagen_serv_tres', models.ImageField(default='imagen.jpg', upload_to=prov_servis.models.imgpost_directory_path)),
                ('imagen_serv_cuatro', models.ImageField(default='imagen.jpg', upload_to=prov_servis.models.imgpost_directory_path)),
                ('titulo', models.CharField(max_length=200)),
                ('archivo_contenido', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prov_servis.servicio_prov')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='perfil_proveedor.profile_proveedor')),
            ],
            options={
                'verbose_name': 'Post_servs',
            },
        ),
    ]
