# Generated by Django 4.1.5 on 2023-04-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prov_servis', '0002_servicio_prov_descripcion_serv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio_prov',
            name='descripcion_serv',
            field=models.CharField(blank=True, default='NULL', max_length=150, null=True),
        ),
    ]
