# Generated by Django 4.1.7 on 2023-07-04 21:07

from django.db import migrations, models
import prov_servis.models


class Migration(migrations.Migration):
    dependencies = [
        ("prov_servis", "0004_alter_post_prov_imagen_serv_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post_prov",
            name="imagen_serv",
            field=models.ImageField(
                default="NULL",
                max_length=255,
                upload_to=prov_servis.models.imgpost_directory_path,
            ),
        ),
        migrations.AlterField(
            model_name="post_prov",
            name="imagen_serv_cuatro",
            field=models.ImageField(
                default="NULL",
                max_length=255,
                upload_to=prov_servis.models.imgpost_directory_path,
            ),
        ),
        migrations.AlterField(
            model_name="post_prov",
            name="imagen_serv_dos",
            field=models.ImageField(
                default="NULL",
                max_length=255,
                upload_to=prov_servis.models.imgpost_directory_path,
            ),
        ),
        migrations.AlterField(
            model_name="post_prov",
            name="imagen_serv_tres",
            field=models.ImageField(
                default="NULL",
                max_length=255,
                upload_to=prov_servis.models.imgpost_directory_path,
            ),
        ),
    ]
