# Generated by Django 4.1.7 on 2023-04-10 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_vendedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metodo_pago_vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_cobro', models.CharField(blank=True, default='NULL', max_length=50, null=True)),
                ('Nombre_completo_identificacion', models.CharField(blank=True, default='NULL', max_length=100, null=True)),
                ('Numero_cuenta_bancaria', models.CharField(blank=True, default='NULL', max_length=100, null=True)),
                ('creado_m_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_m_en', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pago_afiliado', to='login_vendedor.profile_vendedor')),
            ],
            options={
                'verbose_name': 'metodo_pago_afiliados',
            },
        ),
        migrations.CreateModel(
            name='Direccion_vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provincia_afiliado', models.CharField(default='provincia_afiliado', max_length=30, null=True)),
                ('ciudad_afiliado', models.CharField(default='ciudad_afiliado', max_length=30, null=True)),
                ('sector_afiliado', models.CharField(default='direccion_sector_afiliado', max_length=70, null=True)),
                ('calle_afiliado', models.CharField(default='direccion_sector_afiliado', max_length=70, null=True)),
                ('numero', models.CharField(default='000', max_length=7, null=True)),
                ('apartamento_num', models.CharField(default='00', max_length=7, null=True)),
                ('creado_d_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_d_en', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direccion_afiliado_user', to='login_vendedor.profile_vendedor')),
            ],
            options={
                'verbose_name': 'direccion_afiliados',
            },
        ),
        migrations.CreateModel(
            name='Contacto_vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=20, null=True)),
                ('numeroWhatsapp_afiliado', models.CharField(max_length=20, unique=True)),
                ('creado_c_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_c_en', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contato_afi', to='login_vendedor.profile_vendedor')),
            ],
            options={
                'verbose_name': 'contacto_afiliados',
            },
        ),
    ]
