# Generated by Django 4.1.7 on 2023-04-11 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vend_config_inic', '0002_metodo_pago_vendedor_tipo_document_identificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='metodo_pago_vendedor',
            name='nombre_banco',
            field=models.CharField(blank=True, default='NULL', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='metodo_pago_vendedor',
            name='Numero_cuenta_bancaria',
            field=models.CharField(blank=True, default='XXXX XXXX XXXX', max_length=100, null=True),
        ),
    ]
