# Generated by Django 4.1.7 on 2023-05-16 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_vendedor', '0002_rename_codigo_unico_proveedor_profile_vendedor_codigo_unico_vendedor'),
        ('perfil_proveedor', '0005_profile_proveedor_anio_nacimiento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duda_comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto_mensaage', models.CharField(blank=True, default='Null', max_length=100, null=True)),
                ('texto_mensage', models.CharField(blank=True, default='mensage', max_length=2500, null=True)),
                ('fecha_mensage', models.DateTimeField(auto_now_add=True)),
                ('proveedor_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='perfil_proveedor.profile_proveedor')),
                ('vendedor_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login_vendedor.profile_vendedor')),
            ],
            options={
                'verbose_name': 'duda_comentario',
                'verbose_name_plural': 'duda_comentarios',
            },
        ),
    ]
