# Generated by Django 4.1.7 on 2023-05-16 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vend_config_inic', '0003_metodo_pago_vendedor_nombre_banco_and_more'),
        ('vendedor_perfil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='duda_comentario',
            name='contact_vend_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vend_config_inic.contacto_vendedor'),
        ),
    ]
