# Generated by Django 4.1.7 on 2023-05-18 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Articulo_blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
                ('contenido', models.TextField(blank=True, null=True)),
                ('imagen_segun', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
                ('contenido_segun', models.TextField(blank=True, null=True)),
                ('imagen_tre', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
                ('contenido_tre', models.TextField(blank=True, null=True)),
                ('imagen_cuatro', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
                ('contenido_cuatro', models.TextField(blank=True, null=True)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(default=1, limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.categoria')),
            ],
        ),
    ]
