# Generated by Django 4.1.5 on 2023-05-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_imagenbanner_politicas_paginaprincipal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen_itileria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_banner_one', models.ImageField(upload_to='imagenes_banner/')),
                ('img_banner_two', models.ImageField(upload_to='imagenes_banner/')),
                ('img_banner_three', models.ImageField(upload_to='imagenes_banner/')),
            ],
        ),
    ]
