# Generated by Django 4.1.5 on 2023-05-24 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_imagen_itileria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen_itileria',
            name='img_banner_one',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_banner/'),
        ),
        migrations.AlterField(
            model_name='imagen_itileria',
            name='img_banner_three',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_banner/'),
        ),
        migrations.AlterField(
            model_name='imagen_itileria',
            name='img_banner_two',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_banner/'),
        ),
    ]
