# Generated by Django 4.1.7 on 2023-04-01 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perfil_proveedor', '0005_profile_proveedor_anio_nacimiento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion_proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provicia', models.CharField(default='provincia', max_length=50, null=True)),
                ('ciudad', models.CharField(default='Ciudad', max_length=50, null=True)),
                ('calle', models.CharField(default='Calle', max_length=50, null=True)),
                ('numero', models.CharField(default='Numero', max_length=10, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ubicacion_proveedor', to='perfil_proveedor.profile_proveedor')),
            ],
            options={
                'verbose_name': 'ubicacion_proveedores',
            },
        ),
        migrations.CreateModel(
            name='Rango_servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geo_servicio', models.CharField(default='Null', max_length=50, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geo_servicio', to='perfil_proveedor.profile_proveedor')),
            ],
            options={
                'verbose_name': 'rango_servicios',
            },
        ),
        migrations.CreateModel(
            name='Contacto_proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numWhatsapp', models.CharField(max_length=20, null=True)),
                ('telefono', models.CharField(max_length=20, unique=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacto_proveedor', to='perfil_proveedor.profile_proveedor')),
            ],
            options={
                'verbose_name': 'contacto_proveedores',
            },
        ),
    ]
