# Generated by Django 4.1.5 on 2023-04-05 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_inicial_prov', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto_proveedor',
            name='numWhatsapp',
            field=models.CharField(default='000 000 0000', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contacto_proveedor',
            name='telefono',
            field=models.CharField(default='000 000 0000', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='rango_servicio',
            name='geo_servicio',
            field=models.CharField(default='Geo', max_length=50, null=True),
        ),
    ]
