# Generated by Django 4.1.7 on 2023-04-05 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil_proveedor', '0005_profile_proveedor_anio_nacimiento_and_more'),
        ('config_inicial_prov', '0002_alter_contacto_proveedor_numwhatsapp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto_proveedor',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacto_prov', to='perfil_proveedor.profile_proveedor'),
        ),
        migrations.AlterField(
            model_name='rango_servicio',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geo_servis', to='perfil_proveedor.profile_proveedor'),
        ),
        migrations.AlterField(
            model_name='ubicacion_proveedor',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ubicacion_prov', to='perfil_proveedor.profile_proveedor'),
        ),
    ]
