# Generated by Django 4.1.7 on 2023-04-06 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_inicial_prov', '0003_alter_contacto_proveedor_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto_proveedor',
            name='numWhatsapp',
            field=models.CharField(default='000 000', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contacto_proveedor',
            name='telefono',
            field=models.CharField(default='000 000', max_length=20, unique=True),
        ),
    ]
