# Generated by Django 4.1.7 on 2023-07-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("config_inicial_prov", "0004_alter_contacto_proveedor_numwhatsapp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contacto_proveedor",
            name="telefono",
            field=models.CharField(default="000 000", max_length=20),
        ),
    ]
