# Generated by Django 4.1.7 on 2023-04-13 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_vendedor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile_vendedor',
            old_name='codigo_unico_proveedor',
            new_name='codigo_unico_vendedor',
        ),
    ]
