# Generated by Django 4.1.7 on 2023-03-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil_proveedor', '0003_alter_profile_proveedor_codigo_unico_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_proveedor',
            name='codigo_unico_proveedor',
            field=models.CharField(editable=False, max_length=7, unique=True, verbose_name='Código Único'),
        ),
    ]
